### PR TITLE
Add breadcrumb component

### PR DESCRIPTION
**Pull request by goncaloacbsilva**
### About Me:
I'm a comp. sci student interested in fullstack development. I started with React development but changed to Angular because I was tired of react state architecture ahahah
Flowbite was also a game changer for my projects and I've been using it since I discovered it!
In my opinion, Angular lacks open-source **good-looking** component libraries (not counting PrimeNG) and I believe this project will help address that issue. So I would love to give my contribute to the project!

### Changes:
- Added Breadcrumb and BreadcrumbItem components
- Added Breadcrumb docs

### Additional Notes:
- ~~The breadcrumb's main component `<flowbite-breadcrumb>` is barely customizable. Only has the _solidBackground_ property (see related docs)~~
- ~~Could not find any icon for the breadcrumb component on the Tailwind SVG icons pack [Hero Icons](https://heroicons.dev/)~~
- No UI test was created for the component (only the default ones)

### CODE REVIEW

**Comment by goncaloacbsilva** [comment]
### PR Updates:
- Reduced Breadcrumb component complexity
- Removed _solidBackground_ property (User applies styles with class attribute instead)
- Added component sidebar icon that is being used on React version

**Review by bacali95 — APPROVED** [review]
Hello @goncaloacbsilva, great job out there :clap: 
I will merge this.

**Pull request merged**
